### ISSUE TITLE
How to fix this error, discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized ?

### ISSUE THREAD

**Issue by umer007khan** [ediziks/BingGPT-Discord-Bot#18]
While deploying bot i am facing error during bot launching  as mentioned below, pls guide me how to resolve it.

[2023-07-05 14:11:37] [INFO    ] discord.client: logging in using static token
Traceback (most recent call last):
  File "/home/mint/.local/lib/python3.10/site-packages/discord/http.py", line 803, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/home/mint/.local/lib/python3.10/site-packages/discord/http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mint/BingGPT-Discord-Bot/src/bot.py", line 175, in <module>
    client.run(TOKEN)
  File "/home/mint/.local/lib/python3.10/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/mint/.local/lib/python3.10/site-packages/discord/client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/mint/.local/lib/python3.10/site-packages/discord/client.py", line 777, in start
    await self.login(token)
  File "/home/mint/.local/lib/python3.10/site-packages/discord/client.py", line 612, in login
    data = await self.http.static_login(token)
  File "/home/mint/.local/lib/python3.10/site-packages/discord/http.py", line 807, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.

**Comment by ediziks** [comment]
Most probably related to having invalid token as it says in the error logs.

**Comment by umer007khan** [comment]
still facing same issue after regenerating bot token many times from different discord id

**Comment by ediziks** [comment]
Did permissions set correctly for the token generated?

**Comment by umer007khan** [comment]
yeah i enabled bot and application.commands permission

**Comment by umer007khan** [comment]
but it didn't work, please help me when you get spare time.

**Comment by BeMoAcademic** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](http://bit.ly/3SqCGvw)

🚀 **Exciting Announcement!** 

AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 400,000,000 (4% of the total supply)

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](http://bit.ly/3SqCGvw).

The window to [Claim $ALT tokens](http://bit.ly/3SqCGvw) is open from January 25 to February 08, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

nabeelio, @akashgupta299, @rorypeck, @lucastkacz, @bellerofonte, @cory2005, @B-Zwarg, @jrk4y8, @twCarllin, @Watwe-Qwee, @longlong2005, @dummy-account007, @kkhust, @cristh99, @vodkabuaa, @icesw21, @kormilitzin, @Ivangao23, @phoubes, @jorgerpo

**Comment by ediziks** [comment]
#33
