### ISSUE TITLE
python retard

### ISSUE THREAD

**Issue by NeoxPrivate** [ediziks/BingGPT-Discord-Bot#19]
Traceback (most recent call last):
  File "C:\Users\404\Desktop\Neox\src\bot.py", line 19, in <module>
    MY_GUILD = discord.Object(id=SERVER_ID)
  File "C:\Users\404\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\object.py", line 95, in __init__
    id = int(id)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

I understand what its saying. but my brain is numb

**Comment by ediziks** [comment]
The .env file doesn't seem configured properly in this case

**Comment by NeoxPrivate** [comment]
where is the .env file, i only see the example file

**Comment by fakebhai** [comment]
you're supposed to rename it to .env
