### ISSUE TITLE
Run chatbot on Cpanel

### ISSUE THREAD

**Issue by propoka** [ediziks/BingGPT-Discord-Bot#20]
hello, i have a issue when run "python src/bot.py".
Please help me. Thank you.
```
Traceback (most recent call last):
  File "/home/axvktbno/pokav2/BingGPT-Discord-Bot/src/bot.py", line 44, in <module>
    gptbot = Chatbot(cookie_path='cookies.json')
  File "/home/axvktbno/pokav2/BingGPT-Discord-Bot/src/EdgeGPT.py", line 604, in __init__
    _Conversation(self.cookies, self.proxy),
  File "/home/axvktbno/pokav2/BingGPT-Discord-Bot/src/EdgeGPT.py", line 321, in __init__
    self.session.cookies.set(cookie["name"], cookie["value"])
TypeError: string indices must be integers
```

**Comment by ediziks** [comment]
#33
