### ISSUE TITLE
Replit Bing, I have beta access though is there a fix to this

### ISSUE THREAD

**Issue by 6Xian9** [ediziks/BingGPT-Discord-Bot#21]
Traceback (most recent call last):
  File "BingGPT-Discord-Bot/src/main.py", line 394, in create
    self.struct = response.json()
  File "/home/runner/ImpressionableHandmadePcboard/venv/lib/python3.10/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "BingGPT-Discord-Bot/src/main.py", line 880, in <module>
    main()
  File "BingGPT-Discord-Bot/src/main.py", line 876, in main
    asyncio.run(async_main(args))
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "BingGPT-Discord-Bot/src/main.py", line 741, in async_main
    bot = await Chatbot.create(proxy=args.proxy, cookies=args.cookies)
  File "BingGPT-Discord-Bot/src/main.py", line 626, in create
    await _Conversation.create(self.cookies, self.proxy),
  File "BingGPT-Discord-Bot/src/main.py", line 396, in create
    raise Exception(
Exception: Authentication failed. You have not been accepted into the beta.
![image](https://github.com/ediziks/BingGPT-Discord-Bot/assets/115960237/28ac42e5-5c1b-462b-b6b8-52913e502476)

**Comment by ediziks** [comment]
#33
