### ISSUE TITLE
Error - TypeError: 'builtin_function_or_method' object is not subscriptable

### ISSUE THREAD

**Issue by Bonhovis** [ediziks/BingGPT-Discord-Bot#29]
@ediziks I was getting the below error. Windows 10.

```
PS D:\Downloads\Discord\bots\BingGPT-Discord-Bot-main> python src/bot.py
Traceback (most recent call last):
  File "D:\Downloads\Discord\bots\BingGPT-Discord-Bot-main\src\bot.py", line 44, in <module>
    gptbot = Chatbot(cookie_path='cookies.json')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\Discord\bots\BingGPT-Discord-Bot-main\src\EdgeGPT.py", line 603, in __init__
    self.chat_hub: _ChatHub = _ChatHub(
                              ^^^^^^^^^
  File "D:\Downloads\Discord\bots\BingGPT-Discord-Bot-main\src\EdgeGPT.py", line 415, in __init__
    conversation_signature=conversation.struct.get["conversationSignature"],
                           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'builtin_function_or_method' object is not subscriptable
```

Had to change line 415 to the following to get it working:

```
conversation_signature=conversation.struct.get("conversationSignature")
```

**Comment by estrizal** [comment]
same error in ubuntu

**Comment by ediziks** [comment]
Thanks for notifying about the issue. It is now fixed on [main](https://github.com/ediziks/BingGPT-Discord-Bot/commit/4ac54a3acfd48252fc91ec5d7f07490d3ba3d3be).
