### ISSUE TITLE
Connects, but doesn't work

### ISSUE THREAD

**Issue by destyntv** [ediziks/BingGPT-Discord-Bot#9]
My bot connects, and tries to respond but... it blows on my cmd

![image](https://user-images.githubusercontent.com/131536821/234350993-7b04bfb7-82e1-4e1e-aef0-ac77ad3c9a35.png)

[2023-04-25 13:00:04] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'reset'
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\Downloads\New folder\BotDIscord\BingGPT-Discord-Bot\dcbot\bot.py", line 134, in reset
    await interaction.response.send_message("Alfred conversation has been reset")
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\interactions.py", line 778, in send_message
    await adapter.create_interaction_response(
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\webhook\async_.py", line 221, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 40060): Interaction has already been acknowledged.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\app_commands\commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\app_commands\commands.py", line 860, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'reset' raised an exception: HTTPException: 400 Bad Request (error code: 40060): Interaction has already been acknowledged.

**Comment by ediziks** [comment]
Most probably there's something wrong with `cookies.json`. Please check and try again if it helps.

**Comment by xrmaalk** [comment]
Hi there. I am having the same issue. 

What could be wrong with the cookies? Everything seems fine. 

Exported cookies directly from the cookies editor. I tried it again with the session box checked, yet, still getting the same issue when loading responses..... My conversationSignature is set to None since the key was not found in the dict after adjusting to .struct.get('coversationSignature') to workaround an inital keyError.

screenshot.
![image](https://github.com/ediziks/BingGPT-Discord-Bot/assets/33601035/9853b8ac-5a40-4cfe-a909-a1a42749477c)

**Comment by YoukaiCat** [comment]
I can confirm the issue. /ask command throws an exception

![screen](https://github.com/ediziks/BingGPT-Discord-Bot/assets/1074478/f7217d13-ca4c-4953-816f-8afa4cce699d)
